### ISSUE TITLE
Initialize the i40e DPDK driver without huge pages

### ISSUE THREAD

**Issue by aroulin** [ix-project/ix#10]
See comment here: https://github.com/ix-project/ix/pull/6#discussion-diff-88485584L62

**Comment by aroulin** [comment]
It is the admin queue code that first fails when disabling huge pages for DPDK. The code for the admin queue init has plenty of calls to `i40e_allocate_dma_mem` like here: https://github.com/emmericp/dpdk/blob/master/drivers/net/i40e/base/i40e_adminq.c#L84

which in turns calls `rte_memzone_reserve_bounded` with a page size of 2MB.
https://github.com/emmericp/dpdk/blob/5c44fc144dd4fd0b54da98cc12ee143e149b5fa0/drivers/net/i40e/i40e_ethdev.c#L3319

That memory allocation function seems to assume DPDK uses huge pages as page size of 4KB cannot be passed as parameter, only larger page sizes.
http://dpdk.org/doc/api-2.2/rte__memzone_8h.html#a9cb3cbb228a8ba9ccc5e5efbd000b2ef

**Comment by prekageo** [comment]
Does DPDK have any parameter to limit the number of huge pages it tries to reserve in order to speed up the boot time?
