### ISSUE TITLE
"ixev: ran out of receive memory" when testing the echoserver application

### ISSUE THREAD

**Issue by zorun** [ix-project/ix#12]
Hi,

I successfully installed and ran IX on Debian jessie with the default 3.16.36 kernel.  The echoserver application seems to work fine.

However, when I tried to load the echoserver using `nc 192.168.40.1 1234 < /dev/zero > /dev/null`, the echoserver immediately becomes unresponsive (after sending a bunch of TCP responses, it stops responding to any TCP or ICMP queries) and prints this in its log:

```
# ./dp/ix -- ./apps/echoserver 4
...
ixev: ran out of receive memory
CPU 00| 15:55:10 <2>: init: failed to start sandbox
```
I then have to kill the process (^C) and launch it again.

I used the installation and configuration method from the README, on a Intel 82599ES NIC.

I tried to increase the value in `/sys/devices/system/node/node*/hugepages/hugepages-2048kB/nr_hugepages` to 16000, but that did not seem to have an effect (except that it reserved 64 GB of RAM on the system)

**Comment by zorun** [comment]
The full log of running echoserver (with the "out of memory" at the end) is here: http://paste.debian.net/hidden/2a90843d/

The system has two Xeon E5-2630 v3 @ 2.40GHz, each with 8 cores / 16 threads, so that's 32 threads in total.  It has 128 GB of RAM.

By the way, this system has two 82599ES NIC, so I connect both of them to the same switch, and I use ixgbe on the first NIC and IX on the second NIC.  This way, I can communicate with IX from the same system (packets go out through eth0, through the switch, and come back via the second NIC which is running IX).  I don't think it changes anything (compared to using a second system to generate traffic).

**Comment by zorun** [comment]
I played with `IXEV_RECV_DEPTH`, still with 16000 hugepages per core, and stressing `echoserver` with `nc 192.168.40.1 1234 < /dev/zero > /dev/null`.

Here is the result:

- `IXEV_RECV_DEPTH=8192`: echoserver crashed with `dune: exit due to EPT violation`
- `IXEV_RECV_DEPTH=2048`: no crash but no network connectivity
- `IXEV_RECV_DEPTH=1500`: the test worked, nc sent/received at about 150 MiB/s (around 100 kpps)
- however, when increasing `net.core.wmem_max` from 4194304 (default value) to 16000000 for the sender, the "out of receive memory" problem showed up again

All this points towards ixev failing to handle large bursts of data on a single TCP connection.

**Comment by prekageo** [comment]
It seems that you are performing a flood experiment. Unfortunately, IX does not implement flow control at the moment.
