### ISSUE TITLE
Cannot compile IX 

### ISSUE THREAD

**Issue by ghost** [ix-project/ix#13]
I successfully compiled all IX dependencies (with minor modifications to DPDK to compile with gcc 6), but I get an error when linking the IX binary:

user@machine:~/ix$ make -j64
make -C dp
make[1]: Entering directory '/home/user/ix/dp'
gcc -T ix.ld -o ix  core/ethdev.o   core/ethfg.o   core/ethqueue.o   core/cfg.o   core/control_plane.o   core/cpu.o   core/init.o   core/log.o   core/mbuf.o   core/mem.o   core/mempool.o   core/page.o   core/pci.o   core/utimer.o   core/syscall.o   core/timer.o   core/vm.o   core/dpdk.o drivers/ixgbe.o   drivers/i40e.o   drivers/common.o lwip/inet_chksum.o   lwip/ip4_addr.o   lwip/memp_min.o   lwip/misc.o   lwip/pbuf.o net/arp.o   net/dump.o   net/icmp.o   net/ip.o   net/net.o   net/tcp.o   net/tcp_in.o   net/tcp_out.o   net/tcp_api.o   net/udp.o sandbox/main.o   sandbox/umm.o   sandbox/trap.o   sandbox/exec.o ../deps/dune/libdune/libdune.a  -Wl,-whole-archive ../deps/dpdk/build/lib/librte_pmd_ixgbe.a -Wl,-no-whole-archive -Wl,-whole-archive ../deps/dpdk/build/lib/librte_pmd_i40e.a -Wl,-no-whole-archive ../deps/dpdk/build/lib/libethdev.a ../deps/dpdk/build/lib/librte_mbuf.a ../deps/dpdk/build/lib/librte_eal.a ../deps/dpdk/build/lib/librte_mempool.a ../deps/dpdk/build/lib/librte_ring.a -lrt -lpthread -lm -lnuma -ldl -lconfig
/usr/bin/ld: ../deps/dune/libdune/libdune.a(entry.o): relocation R_X86_64_32S against `.text' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: ../deps/dune/libdune/libdune.a(dune.o): relocation R_X86_64_32S against symbol `dune_syscall_handler' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
Makefile:83: recipe for target 'ix' failed
make[1]: *** [ix] Error 1
make[1]: Leaving directory '/home/user/ix/dp'
Makefile:30: recipe for target 'dp' failed
make: *** [dp] Error 2

I recompiled each object in libdune.a with "-fPIC" added to CFLAGS (and also created a similar rule for the .S extension), but the result is still the same. I believe this may be related to an upgrade to gcc 6.2, since I recall compiling it in Ubuntu 16.04 with gcc 5 and did not have this issue. I am using kernel version 4.4.0-51-generic.

Any ideas?

**Comment by prekageo** [comment]
At the moment, we support Ubuntu 16.04 LTS and the tools that come with it. Of course, we welcome patches to add support for more platforms and/or compilers.

**Comment by ghost** [comment]
GCC changes were made in Ubuntu 16.10 (see https://wiki.ubuntu.com/SecurityTeam/PIE). 

The following patch fixed issue:

diff --git a/dp/Makefile b/dp/Makefile
index 77287a3..21e9dd5 100644
--- a/dp/Makefile
+++ b/dp/Makefile
@@ -43,6 +43,12 @@ ifneq ($(ENABLE_KSTATS),)
 CFLAGS += -DENABLE_KSTATS
 endif
 
+# Hardened GCC enables PIE by default
+ifneq ($(shell $(CC) -dumpspecs 2>/dev/null | grep -e no-pie),)
+CFLAGS += -fno-pie
+LDFLAGS += -no-pie
+endif
+
 SRCS =
 DIRS = core drivers lwip net sandbox

**Comment by prekageo** [comment]
Thanks @zooolander for the fix. Would you like to do a pull request? If not, I can just commit your fix.

**Comment by ghost** [comment]
@prekageo, you can go ahead and commit the fix. Thanks
