### ISSUE TITLE
About the static mem address

### ISSUE THREAD

**Issue by geanv** [ix-project/ix#19]
Dear authors,

I tested ix on my testbed (with Intel(R) Xeon(R) CPU E5-2650 v3 @ 2.30GHz, 128GB memory, Intel x520 10Gbps). The mempool cannot be initialized for "pending_pkt".
The call trace is as follows:
`arp_init->mempool_create_datastore->mem_alloc_pages->__mem_alloc_pages->mmap (return MAP_FAILED)`

I guess if fails because the base mem (MEM_PHYS_BASE_ADDR - PGSIZE_2MB * nr) is not suitable for my server. How should I modify the mem addr for my testbed? For example:
`#define MEM_PHYS_BASE_ADDR 0x4000000000`

Many thanks!

**Comment by prekageo** [comment]
Can you provide the output of `cat /proc/self/maps`?

Also, can you apply this patch and provide the output?
```
diff --git a/dp/core/mempool.c b/dp/core/mempool.c
index a012769..4b7a377 100644
--- a/dp/core/mempool.c
+++ b/dp/core/mempool.c
@@ -201,6 +201,11 @@ int mempool_create_datastore(struct mempool_datastore *mds, int nr_elems, size_t
        assert((chunk_size & (chunk_size - 1)) == 0);
        assert(((nr_elems / chunk_size) * chunk_size) == nr_elems);

+       FILE *f = fopen("/proc/self/maps", "r");
+       char buf[4096];
+       int len;
+       while (len = fread(buf, 1, 4096, f))
+               fwrite(buf, 1, len, stdout);

        if (!elem_len || !nr_elems)
                return -EINVAL;
```

**Comment by geanv** [comment]
Thanks!
We solved this problem by using another physical server.
