### ISSUE TITLE
Can I deploy more than one IX instance on one machine?

### ISSUE THREAD

**Issue by hefq343** [ix-project/ix#2]
Hi
  As the title, can I deploy more than one IX instance on one machine? If do, how to deploy it?

**Comment by bernardgut** [comment]
Hi,

This feature isn't supported in the current release.
- Bernard

**Comment by Yourens** [comment]
Why not?

**Comment by prekageo** [comment]
This is a feature that we'd like to have but unfortunately is not our top priority at the moment. Contributions are welcome, though.
