### ISSUE TITLE
There are some errors when I start the ix

### ISSUE THREAD

**Issue by tianshuh** [ix-project/ix#20]
I have met some errors when I start the IX, and I can't fix it.
1. I can't write 4096 in huge-pages just because the memory isn't enough. If IX need 2G, why should we write 4096 in the 2048-hugepage?
2. There is something wrong with:
EAL: PCI device 0000:03:00.0 on NUMA socket -1
EAL:   probe driver: 8086:151c rte_ixgbe_pmd
EAL:   Not managed by a supported kernel driver, skipped
EAL: PCI device 0000:03:00.1 on NUMA socket -1
EAL:   probe driver: 8086:151c rte_ixgbe_pmd
EAL:   Not managed by a supported kernel driver, skipped

My environment is: Ubuntu 16.04 LTS   Intel Corporation 82599 10 Gigabit TN Network Connection (rev 01) 

Here is the log:
20:34:47 <4>: init: starting IX
20:34:47 <4>: init: cpu phase
20:34:47 <4>: cpu: detected 12 cores
20:34:47 <4>: init: module CPU        SUCESS
20:34:47 <4>: init: module Dune       SUCESS
20:34:48 <4>: timer: detected 2400 ticks per US
20:34:48 <4>: init: module timer      SUCESS
mempool_datastore: pending_pkt     pages:   1 elem_len:  56 nostraddle:0 chunk_size:128 num_chun
ks:4292mempool_datastore: arp             pages:   3 elem_len:  80 nostraddle:0 chunk_size:128 num_chun
ks:461420:34:48 <4>: init: module net        SUCESS
20:34:48 <4>: using config :'./ix.conf'
20:34:48 <4>: no static arp entries defined in config
20:34:48 <4>: net: using the following configuration:
20:34:48 <4>: 	host IP:	172.18.53.10
20:34:48 <4>: 	broadcast IP:	172.18.255.255
20:34:48 <4>: 	gateway IP:	172.18.0.254
20:34:48 <4>: 	subnet mask:	255.255.0.0
20:34:48 <4>: init: module cfg        SUCESS
20:34:48 <4>: init: module cp         SUCESS
EAL: Detected lcore 0 as core 0 on socket 1
EAL: Detected lcore 1 as core 1 on socket 1
EAL: Detected lcore 2 as core 2 on socket 1
EAL: Detected lcore 3 as core 8 on socket 1
EAL: Detected lcore 4 as core 9 on socket 1
EAL: Detected lcore 5 as core 10 on socket 1
EAL: Detected lcore 6 as core 0 on socket 0
EAL: Detected lcore 7 as core 1 on socket 0
EAL: Detected lcore 8 as core 2 on socket 0
EAL: Detected lcore 9 as core 8 on socket 0
EAL: Detected lcore 10 as core 9 on socket 0
EAL: Detected lcore 11 as core 10 on socket 0
EAL: Support maximum 128 logical core(s) by configuration.
EAL: Detected 12 lcore(s)
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL:   IOMMU type 1 (Type 1) is supported
EAL:   IOMMU type 8 (No-IOMMU) is not supported
EAL: VFIO support initialized
EAL: Setting up physically contiguous memory...
EAL: Ask a virtual area of 0x30400000 bytes
EAL: Virtual area found at 0x7fce2f800000 (size = 0x30400000)
EAL: Ask a virtual area of 0x81400000 bytes
EAL: Virtual area found at 0x7fcdae200000 (size = 0x81400000)
EAL: Ask a virtual area of 0x200000 bytes
EAL: Virtual area found at 0x7fcdade00000 (size = 0x200000)
EAL: Ask a virtual area of 0x12a800000 bytes
EAL: Virtual area found at 0x7fcc83400000 (size = 0x12a800000)
EAL: Ask a virtual area of 0x1e7400000 bytes
EAL: Virtual area found at 0x7fca9be00000 (size = 0x1e7400000)
EAL: Ask a virtual area of 0x200000 bytes
EAL: Virtual area found at 0x7fca9ba00000 (size = 0x200000)
EAL: Ask a virtual area of 0x400000 bytes
EAL: Virtual area found at 0x7fca9b400000 (size = 0x400000)
EAL: Ask a virtual area of 0x400000 bytes
EAL: Virtual area found at 0x7fca9ae00000 (size = 0x400000)
EAL: Ask a virtual area of 0x200000 bytes
EAL: Virtual area found at 0x7fca9aa00000 (size = 0x200000)
EAL: Requesting 37 pages of size 2MB from socket 0
EAL: Requesting 37 pages of size 2MB from socket 1
EAL: TSC frequency is ~2400085 KHz
EAL: Master lcore 0 is ready (tid=655158c0;cpuset=[0])
EAL: lcore 11 is ready (tid=5d4f5700;cpuset=[11])
EAL: lcore 8 is ready (tid=5ecf8700;cpuset=[8])
EAL: lcore 6 is ready (tid=5fcfa700;cpuset=[6])
EAL: lcore 9 is ready (tid=5e4f7700;cpuset=[9])
EAL: lcore 1 is ready (tid=624ff700;cpuset=[1])
EAL: lcore 3 is ready (tid=614fd700;cpuset=[3])
EAL: lcore 2 is ready (tid=61cfe700;cpuset=[2])
EAL: lcore 7 is ready (tid=5f4f9700;cpuset=[7])
EAL: lcore 4 is ready (tid=60cfc700;cpuset=[4])
EAL: lcore 5 is ready (tid=604fb700;cpuset=[5])
EAL: lcore 10 is ready (tid=5dcf6700;cpuset=[10])
EAL: PCI device 0000:03:00.0 on NUMA socket -1
EAL:   probe driver: 8086:151c rte_ixgbe_pmd
EAL:   Not managed by a supported kernel driver, skipped
EAL: PCI device 0000:03:00.1 on NUMA socket -1
EAL:   probe driver: 8086:151c rte_ixgbe_pmd
EAL:   Not managed by a supported kernel driver, skipped
20:34:52 <4>: init: module dpdk       SUCESS
CPU 06| 20:34:52 <4>: cpu: started core 6, numa node 0
fatal exception 13, code 0 - dying...
dune: --- Begin Trap Dump ---
dune: RIP 0x000000007000d7f5
dune: CS 0x10 SS 0x18
dune: ERR 0x00000000 RFLAGS 0x00010246
dune: RAX 0x0000000000000000 RCX 0x0000000000000606
dune: RDX 0x0000000000000000 RBX 0x0000000000000000
dune: RSP 0x00007ffdf2d24eb0 RBP 0x00000000700b3242
dune: RSI 0x0000000000000037 RDI 0x00007ffdf2d24390
dune: R8  0x0000000000000000 R9  0x0000000000000037
dune: R10 0x0000000000000037 R11 0x0000000000000000
dune: R12 0x0000000000000004 R13 0x00007ffdf2d24fc8
dune: R14 0x0000000000000000 R15 0x0000000000000000
dune: Dumping Stack Contents...
dune: RSP+0  0x00000000700b33c8
dune: RSP+8  0x0000000070009cca
dune: RSP+16 0x00000000700b25c0
dune: RSP+24 0x0000000000000000
dune: RSP+32 0x00000000700b25c0
dune: RSP+40 0x000000007000a0d0
dune: RSP+48 0x00007ffdf2d24fc0
dune: RSP+56 0x00007fce64523830
dune: RSP+64 0xffffffffff000000
dune: RSP+72 0x00007ffdf2d24fc8
dune: RSP+80 0x0000000400000000
dune: RSP+88 0x0000000070009c70
dune: code before IP	77 b7 3a 00 e8 f6 fa ff ff 85 c0 89 c3 75 3a b9 06 06 00 00 
dune: code at IP	0f 32 89 c1 66 0f ef c0 81 e1 00 1f 00 00 b8 01 00 00 00 48 
dune: --- End Trap Dump ---

**Comment by prekageo** [comment]
IX fails on this line `msr_val = rdmsr(MSR_RAPL_POWER_UNIT);`. What is your CPU model? Can you provide the output of `/proc/cpuinfo`?

**Comment by tianshuh** [comment]
ok!

processor	: 11
vendor_id	: GenuineIntel
cpu family	: 6
model		: 44
model name	: Intel(R) Xeon(R) CPU           E5645  @ 2.40GHz
stepping	: 2
microcode	: 0x13
cpu MHz		: 2400.005
cache size	: 12288 KB
physical id	: 0
siblings	: 6
core id		: 10
cpu cores	: 6
apicid		: 20
initial apicid	: 20
fpu		: yes
fpu_exception	: yes
cpuid level	: 11
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall
 nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 popcnt aes lahf_lm tpr_shadow vnmi flexpriority ept vpid dtherm aratbugs		:
bogomips	: 4800.22
clflush size	: 64
cache_alignment	: 64
address sizes	: 40 bits physical, 48 bits virtual
[cpuinfo.txt](https://github.com/ix-project/ix/files/909534/cpuinfo.txt)


power management:

**Comment by prekageo** [comment]
This is an old CPU. Unfortunately, it is unsupported in IX at the moment. You can try to comment out calls to `rdmsr()` that refer to power thermal management:
- `dp/core/init.c:499`
- `dp/core/ethqueue.c:195`

Let us know how this works out for you.

**Comment by tianshuh** [comment]
OK. I'll try now and tell you how it works later. Thank you!

**Comment by tianshuh** [comment]
Hi prekageo,  I comment the two lines and it succeeds. Thank you very much!
