### ISSUE TITLE
Echoclient change

### ISSUE THREAD

**Issue by kkaffes** [ix-project/ix#23]
I have changed the code of the echoclient so that it prints out results every 10 seconds instead of waiting for input. Is this something you would be interested to merge into master?

**Comment by marioskogias** [comment]
The behaviour of the echoclient complies with the benchmarking infrastructure.
Check https://github.com/ix-project/ix-bench/ for more info.

If you want this extra functionality open a pull request, but please don't break backwards compatibility. This should be controlled by a cmd parameter, but the default behaviour should remain as is.
