### ISSUE TITLE
support for mlx4 driver?

### ISSUE THREAD

**Issue by yilongli** [ix-project/ix#24]
I am interested in this because I use the m510 machines on CloudLab (http://docs.cloudlab.us/hardware.html#%28part._cloudlab-utah%29) regularly in research and these machines have Mellanox ConnectX-3 10Gb Ethernet cards.

I would also like to know more about the efforts required to support a new type of NIC. For example, I notice that the sizes of ```dp/drivers/{ixgbe,i40e}.c``` are pretty small. 

Thanks!

**Comment by prekageo** [comment]
If the mlx4 is supported by DPDK, then it is easy to support this driver on IX. the `dp/drivers` files are small wrappers around DPDK functions. The only part which is different (for performance and compatibility reasons) is the RX/TX path. We would be happy to accept your pull request if you decide to add support for mlx4.

**Comment by prekageo** [comment]
I assume that you are no longer interested in this issue. If that's not the case, please re-open it.
