### ISSUE TITLE
Minor documentation inconsistencies

### ISSUE THREAD

**Issue by llvilanova** [ix-project/ix#27]
Hi! The top-level `README.md` file says to use `git submodule update --init` to fetch the project's dependencies, whereas (at least) the `Requirements` and `Getting-started` wiki pages point to using the `deps/fetch-deps.sh` script (which is not on the repo any more).

**Comment by prekageo** [comment]
Thanks for catching this. For the moment, I disable the wiki because nobody has maintained it in the past year or so.
