### ISSUE TITLE
Simpler and more flexible physical device assignment instructions

### ISSUE THREAD

**Issue by llvilanova** [ix-project/ix#28]
Both the wiki and readme tell the user to remove the `ixgbe` device to make it available to IX. That's not always possible if we have other NICs that require the same driver on the host.

Instead, it's better to rebind a device's driver. That can be accomplished through DPDK's `dpdk-devbind.py`script (http://dpdk.org/doc/guides/tools/devbind.html).

**Comment by prekageo** [comment]
Updated the README file to correctly describe the initialization process. Commit 550bf28a4ddd5fafcec707a14acd502712a10dae
