### ISSUE TITLE
Ethernet device initialization error

### ISSUE THREAD

**Issue by kkaffes** [ix-project/ix#29]
After commit 6ba626c I get the following error:

`ix: drivers/common.c:194: driver_init: Assertion 'port < rte_eth_dev_count()' failed.
Aborted`

where `rte_eth_dev_count` is 0.

**Comment by prekageo** [comment]
Updated the README file to correctly describe the initialization process. Commit 550bf28

**Comment by kkaffes** [comment]
Thanks!

**Comment by 3017218211** [comment]
I get the same error with latest version.

ubuntu@ubuntu:~/ix$ sudo ./dp/ix -- ./apps/echoserver 4
06:47:00 <4>: init: starting IX
06:47:00 <4>: init: cpu phase
06:47:00 <4>: init: module Dune       SUCESS
06:47:00 <4>: cpu: detected 2 cores
mempool_datastore: runners         pages:   1 elem_len:  24 nostraddle:0 chunk_size:128 num_chunks:4682 [0x3fffe00000-0x4000000000]
06:47:00 <4>: init: module CPU        SUCESS
06:47:00 <4>: timer: detected 2711 ticks per US
06:47:00 <4>: init: module timer      SUCESS
mempool_datastore: pending_pkt     pages:   1 elem_len:  56 nostraddle:0 chunk_size:128 num_chunks:4292 [0x3fffc00000-0x3fffe00000]
mempool_datastore: arp             pages:   3 elem_len:  80 nostraddle:0 chunk_size:128 num_chunks:4614 [0x3fff600000-0x3fffc00000]
06:47:00 <4>: init: module net        SUCESS
06:47:00 <4>: using config :'./ix.conf'
06:47:00 <4>: no static arp entries defined in config
06:47:00 <4>: net: using the following configuration:
06:47:00 <4>: 	host IP:	192.168.0.21
06:47:00 <4>: 	broadcast IP:	192.168.0.255
06:47:00 <4>: 	gateway IP:	192.168.0.1
06:47:00 <4>: 	subnet mask:	255.255.255.0
06:47:00 <4>: init: module cfg        SUCESS
06:47:00 <4>: init: module cp         SUCESS
06:47:00 <4>: pci: created device 0000:02:01.0, NUMA node -1
06:47:00 <4>: pci:	IOMEM - base fd5c0000, len 20000
06:47:00 <4>: pci:	IOMEM - base fdff0000, len 10000
06:47:00 <4>: init: module pci        SUCESS
EAL: Detected lcore 0 as core 0 on socket 0
EAL: Detected lcore 1 as core 0 on socket 0
EAL: Support maximum 128 logical core(s) by configuration.
EAL: Detected 2 lcore(s)
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: Module /sys/module/vfio_pci not found! error 2 (No such file or directory)
EAL: VFIO modules not loaded, skipping VFIO support...
EAL: Setting up physically contiguous memory...
EAL: Ask a virtual area of 0x200000 bytes
EAL: Virtual area found at 0x7f77bfc00000 (size = 0x200000)
EAL: Ask a virtual area of 0x200000 bytes
EAL: Virtual area found at 0x7f77bf800000 (size = 0x200000)
EAL: Ask a virtual area of 0x12e00000 bytes
EAL: Virtual area found at 0x7f77ac800000 (size = 0x12e00000)
EAL: Ask a virtual area of 0x6800000 bytes
EAL: Virtual area found at 0x7f77a5e00000 (size = 0x6800000)
EAL: Ask a virtual area of 0x4a00000 bytes
EAL: Virtual area found at 0x7f77a1200000 (size = 0x4a00000)
EAL: Ask a virtual area of 0x8000000 bytes
EAL: Virtual area found at 0x7f7799000000 (size = 0x8000000)
EAL: Ask a virtual area of 0x2e00000 bytes
EAL: Virtual area found at 0x7f7796000000 (size = 0x2e00000)
EAL: Ask a virtual area of 0x2c00000 bytes
EAL: Virtual area found at 0x7f7793200000 (size = 0x2c00000)
EAL: Ask a virtual area of 0x1a00000 bytes
EAL: Virtual area found at 0x7f7791600000 (size = 0x1a00000)
EAL: Ask a virtual area of 0x4800000 bytes
EAL: Virtual area found at 0x7f778cc00000 (size = 0x4800000)
EAL: Ask a virtual area of 0x2000000 bytes
EAL: Virtual area found at 0x7f778aa00000 (size = 0x2000000)
EAL: Ask a virtual area of 0x400000 bytes
EAL: Virtual area found at 0x7f778a400000 (size = 0x400000)
EAL: Ask a virtual area of 0x400000 bytes
EAL: Virtual area found at 0x7f7789e00000 (size = 0x400000)
EAL: Ask a virtual area of 0x200000 bytes
EAL: Virtual area found at 0x7f7789a00000 (size = 0x200000)
EAL: Ask a virtual area of 0x200000 bytes
EAL: Virtual area found at 0x7f7789600000 (size = 0x200000)
EAL: Requesting 74 pages of size 2MB from socket 0
EAL: TSC frequency is ~2712014 KHz
EAL: Master lcore 0 is ready (tid=c246b940;cpuset=[0])
06:47:47 <4>: init: module dpdk       SUCESS
ix: drivers/common.c:194: driver_init: Assertion `port < rte_eth_dev_count()' failed.

ubuntu@ubuntu:~$ lspci | grep -i eth
02:01.0 Ethernet controller: Intel Corporation 82545EM Gigabit Ethernet Controller (Copper) (rev 01)

**Comment by prekageo** [comment]
Please create a new issue.
