### ISSUE TITLE
Can not allocate a guest-physically contiguous set of 2MB pages

### ISSUE THREAD

**Issue by feitang0** [ix-project/ix#30]
I want to run IX on SLES 11 sp1 whose kernel version is 2.6.32, and I have modified some kernel code to support Dune and DPDK.
When I start the IX (v1.0), I got this error "page: failed to get machine address for 0x4000000000", the detail is in below:

03:10:11 <4>: init: starting IX
03:10:11 <4>: init: cpu phase
03:10:11 <4>: cpu: detected 12 cores
03:10:11 <4>: init: module CPU        SUCESS
03:10:11 <4>: init: module Dune       SUCESS
03:10:11 <4>: timer: detected 2399 ticks per US
03:10:11 <4>: init: module timer      SUCESS
mempool_datastore: pending_pkt     pages:   1 elem_len:  56 nostraddle:0 chunk_size:128 num_chunks:4292
mempool_datastore: arp             pages:   3 elem_len:  80 nostraddle:0 chunk_size:128 num_chunks:4614
03:10:11 <4>: init: module net        SUCESS
03:10:11 <4>: using config :'./ix.conf'
03:10:11 <4>: no static arp entries defined in config
03:10:11 <4>: net: using the following configuration:
03:10:11 <4>: 	host IP:	172.18.11.234
03:10:11 <4>: 	broadcast IP:	172.18.255.255
03:10:11 <4>: 	gateway IP:	192.168.0.254
03:10:11 <4>: 	subnet mask:	255.255.0.0
03:10:11 <4>: init: module cfg        SUCESS
03:10:11 <4>: init: module cp         SUCESS
EAL: Detected lcore 0 as core 0 on socket 0
EAL: Detected lcore 1 as core 1 on socket 0
EAL: Detected lcore 2 as core 2 on socket 0
EAL: Detected lcore 3 as core 8 on socket 0
EAL: Detected lcore 4 as core 9 on socket 0
EAL: Detected lcore 5 as core 10 on socket 0
EAL: Detected lcore 6 as core 0 on socket 1
EAL: Detected lcore 7 as core 1 on socket 1
EAL: Detected lcore 8 as core 2 on socket 1
EAL: Detected lcore 9 as core 8 on socket 1
EAL: Detected lcore 10 as core 9 on socket 1
EAL: Detected lcore 11 as core 10 on socket 1
EAL: Support maximum 128 logical core(s) by configuration.
EAL: Detected 12 lcore(s)
EAL: Setting up physically contiguous memory...
EAL: WARNING: TSC frequency estimated roughly - clock timings may be less accurate.
EAL: TSC frequency is ~2400128 KHz
EAL: Master lcore 0 is ready (tid=f523da40;cpuset=[0])
EAL: lcore 3 is ready (tid=e8437710;cpuset=[3])
EAL: lcore 4 is ready (tid=e7c36710;cpuset=[4])
EAL: lcore 7 is ready (tid=e6433710;cpuset=[7])
EAL: lcore 2 is ready (tid=e8c38710;cpuset=[2])
EAL: lcore 1 is ready (tid=e9439710;cpuset=[1])
EAL: lcore 10 is ready (tid=e4c30710;cpuset=[10])
EAL: lcore 5 is ready (tid=e7435710;cpuset=[5])
EAL: lcore 6 is ready (tid=e6c34710;cpuset=[6])
EAL: lcore 11 is ready (tid=e442f710;cpuset=[11])
EAL: lcore 9 is ready (tid=e5431710;cpuset=[9])
EAL: lcore 8 is ready (tid=e5c32710;cpuset=[8])
EAL: PCI device 0000:02:00.0 on NUMA socket -1
EAL:   probe driver: 8086:151c rte_ixgbe_pmd
EAL:   Not managed by a supported kernel driver, skipped
EAL: PCI device 0000:02:00.1 on NUMA socket -1
EAL:   probe driver: 8086:151c rte_ixgbe_pmd
EAL:   Not managed by a supported kernel driver, skipped
03:10:15 <4>: init: module dpdk       SUCESS
03:10:15 <4>: sched_setaffinity ret: 0
03:10:15 <4>: cpu_init_percpu pcpu: -10485760
03:10:15 <4>: dune_enter_ex
CPU 00| 20:22:24 <4>: cpu: started core 0, numa node 0
CPU 00| 08:00:00 <4>: init: module firstcpu   SUCESS
CPU 00| 14:28:15 <2>: page: failed to get machine address for 0x4000000000
ix: core/mempool.c:217: mempool_create_datastore: Assertion `mds->buf' failed.
Aborted

I find this error happens at page_alloc_contig_on_node in dp/core/page.c.

Any ideas? Thanks!

**Comment by prekageo** [comment]
Keep in mind that you are using a 7 year old kernel. Try to see if the file /proc/self/pagemap exists.

**Comment by feitang0** [comment]
Thanks! The file exists, but I found that there was a page-mapping error. I will see what's wrong.
