### ISSUE TITLE
Question about the location of LWIP (userspace or kernelspace)

### ISSUE THREAD

**Issue by SungHoHong2** [ix-project/ix#33]
Hello, I have read your paper about IX - Data plane operating system 
and was wondering whether IX project uses TCP stack in userspace or kernel space.

**Comment by prekageo** [comment]
Hi. The TCP stack runs in the IX kernel. That means ring 0 non-root mode.

**Comment by SungHoHong2** [comment]
Thanks for making it clear!

**Comment by SungHoHong2** [comment]
In that case, just one more question, is LWIP running on kernel space originally? or have you guys modified LWIP to work on kernel space?

**Comment by prekageo** [comment]
I don't understand your question. Why wouldn't any piece of software run in kernel space?

**Comment by SungHoHong2** [comment]
Because according to the documents of LWIP, it is designed to run the process in userspace, (However it never mentioned that it was userspace stack) 

Anyway, non root 0 means kernel space for IX not the userspace

**Comment by prekageo** [comment]
Still, I don't understand your question very well.

**Comment by SungHoHong2** [comment]
application == userspace
TCP stack and Hypervisor == kernelspace ?

**Comment by SungHoHong2** [comment]
or is it 
application + TCP stack == userspace 
Hypervisor == kernelspace

**Comment by SungHoHong2** [comment]
So I am asking whether, IX runs like Seastar, mTCP and all the other customized stack that runs on userspace rather than using the stack in kernel space 

or uses the TCP stack in the kernel space like native Socket API

**Comment by prekageo** [comment]
Actually, the answer is neither. I suggest that you read the Dune paper and IX paper. If you still have questions, send me an email. This is not material for a GitHub issue.
