### ISSUE TITLE
How to increase connection concurrency?

### ISSUE THREAD

**Issue by piginthesettingsun** [ix-project/ix#34]
In the paper of IX, it is said that the ix can support up to 250,000 concurrent connections. But I failed to set up more than 64511 connections, and found that the later SYN packets are not responded. It doesn't work to modify the parameter _pp_conn_pool_entries_ in echoserver.c or increase working cores.
So I wonder how can I increase the max connection concurrency?

**Comment by prekageo** [comment]
Hi,
Can you briefly describe your experimental setup?

**Comment by piginthesettingsun** [comment]
I work on a server with 20 cores and 64G memory, compile and set up the environment with README of IX. The number of cpus in ix.conf is tried from 1 to 8. And I also tried to modify `pp_conn_pool_entries` in echoserver.c， which seems related to max concurrency, from 16*4096 as default to 160*4096.
I run IX simply with the command `./dp/ix -- ./apps/echoserver 30` as the message size is 30 Bytes. 
The client is an mTCP based high-performance packet generator, tries to set up 80000 TCP connection and then send echo request, but only 64511 connections are established.

**Comment by prekageo** [comment]
The 4-tuple (src-ip, src-port, dst-ip, dst-port) must be unique in TCP. If you can only modify src-port, then the theoretical limit is 64K max TCP connections. The easiest solution is to use more clients.

**Comment by piginthesettingsun** [comment]
OK, fine, I guess I find the problem. Our client start with src-ip of 192.168.3.20, and
will use a new src-ip 192.168.3.21 after 64511 connections, but I only configured a static ARP entry for 192.168.3.20. So can I configure static ARP entries with mask like `192.168.3.0/24`? (I tried it but doesn't work)

**Comment by prekageo** [comment]
No, you can't use masks in the static ARP entries.

**Comment by piginthesettingsun** [comment]
OK, thank you very much!
And let's go back to the beginning of the question, should I control max concurrency with `pp_conn_pool_entries` in echoserver.c?

**Comment by prekageo** [comment]
Yes, you have to increase it. You can pass it in the command line. No need to modify the source code.

This is the usage of echoserver: https://github.com/ix-project/ix/blob/550bf28a4ddd5fafcec707a14acd502712a10dae/apps/echoserver.c#L162

**Comment by piginthesettingsun** [comment]
Emmmmm, I try to start the program with `./dp/ix -- ./apps/echoserver 30 800000` and set up 500,000 connections from the client, but IX raises error with **_tcp_alloc oom_** after about 260,000 connections are established. The 2M huge pages are configured with the number of 10240 for each NUMA node (42G memory on two NUMA node in total).

**Comment by piginthesettingsun** [comment]
So the IX is limited by 250,000 concurrent connections, as described in paper?

**Comment by prekageo** [comment]
We have definitely tested up to this amount of connections. There are a number of memory limits here and there in the code. You can try to increase them and see how it goes. I would start by grepping for "tcp_alloc oom" and see which limit you are hitting. Try to increase it and move on from there.

**Comment by piginthesettingsun** [comment]
Thank you very much! And I'll also test the IX within this amount of connections first.
