### ISSUE TITLE
IX crashed on startup

### ISSUE THREAD

**Issue by Yourens** [ix-project/ix#4]
I have been trying to run ix these days but IX just crashed on startup.

Here is the crash output:

CPU 00| 00:49:26 <4>: init: barrier after al CPU initialization
CPU 00| 00:49:26 <4>: init: module hw         SUCESS
CPU 00| 00:49:26 <5>: sandbox: env = 'LC_TIME=zh_CN.UTF-8'
CPU 00| 00:49:26 <4>: sandbox: loading segment - va 0x000000000, len 25150
CPU 00| 00:49:26 <4>: sandbox: loading segment - va 0x000225bc0, len 15a8
CPU 00| 00:49:26 <5>: sandbox: entry addr is 6f000cc0
CPU 00| 00:49:26 <5>: sandbox: umm_mmap: addr:7eff801000, len:7ff000, end:7f00000000
dune: exit due to EPT violation

I have tried different system and machines, but all of them didn't work. Mainly I use Ubuntu 16.04 or Ubuntu 15.10 with released kernel or 4.4.x from kernel.org.

I try to trace and figure out the reason of this bug. But it makes things more obscure.
here is the dmsg:
![image](https://cloud.githubusercontent.com/assets/5778943/18414392/8c4e45c2-778b-11e6-83e2-59259406ed9f.png)

I notice the crash occurs at setup_argument function at sandbox/main.c. When access arg_ptr's content, the  vmx_do_ept_fault is invoked. But I think this ept fault should happen when data_ptr is accessed earlier and it points to the same page as art_prt do.

Thank you very much.

**Comment by prekageo** [comment]
Please provide the following:
- command line used to invoke IX
- your IX configuration file
- last 50 lines of dmesg

**Comment by Yourens** [comment]
Hi, Thanks for your reply!!!

Here is the script used to run ix(i.e. command line):
https://gist.github.com/HuaiYuSched/4ed256ba88173c8d714180577d390291
Here is the configuration file:
https://gist.github.com/HuaiYuSched/8c70a3a568bf0bdd8d1af9afcfee84e1
Here is the outputs: 
https://gist.github.com/HuaiYuSched/e882e0d4d277b51e90c887a4fe01591c
Here is dmesg:
Less than 50 line beacuse previous is irrelevant.
https://gist.github.com/HuaiYuSched/07970e7a970f881cfd83f7154b36a1b8

**Comment by prekageo** [comment]
It seems that you have made changes to the source code, thus the RIP register doesn't correspond to a machine instruction when I build IX from the master branch. Please, either:
1. revert your changes, build and post the dmesg output or
2. share your code

**Comment by Yourens** [comment]
No, I just clone the code from the master then Trying to run it. I didn't changed anything.

Thanks very much.

**Comment by prekageo** [comment]
The line `<5>: sandbox: env = 'LC_TIME=zh_CN.UTF-8'` is only printed if you `#define DEBUG`.

Also, there is no code in the master branch that prints this line `<5>: sandbox: umm_mmap: addr:7eff801000, len:7ff000, end:7f00000000`.

In any case, post the output of this command: `objdump -SM intel dp/ix| grep -C30 7001ed60`

**Comment by Yourens** [comment]
Yes, that's the only two place I modified for debugging! 
That's a great suggestion. Here is the result of your command.
https://gist.github.com/HuaiYuSched/05cf3c903aaaf578f306990a6097f00c

Thank you very much.

**Comment by prekageo** [comment]
Please do the following:
- Download [debug_gpa_to_hva.txt](https://github.com/ix-project/ix/files/487410/debug_gpa_to_hva.txt)
- `git -C deps/dune apply < debug_gpa_to_hva.txt`
- `sudo rmmod dune;make -C deps/dune/kern&&sudo insmod deps/dune/kern/dune.ko`
- `sudo ./dp/ix -- ./apps/echoserver 4`
- Post the output of `dmesg | grep -C30 7efffffbe0`

**Comment by prekageo** [comment]
Please also attach the output of this command `awk '//{print}/^$/{exit}' /proc/cpuinfo`

**Comment by Yourens** [comment]
Thanks! 
Here is the dmesg output:
https://gist.github.com/anonymous/71af7fa5627eeced1fec1993e29ac601
I put the cpuinfo in the command in that link.

**Comment by prekageo** [comment]
Your processor supports up to 512 GB of physical address space. Go to file deps/dune/kern/dune.h. Change the GPA_MAP_SIZE to 1<<31 (maybe max 1<<32). We'll try to see if we can come up with a better solution to support old processors.

**Comment by Yourens** [comment]
Thanks for your help! It works now!
