### ISSUE TITLE
Make eth_rx_idle_wait driver independent

### ISSUE THREAD

**Issue by aroulin** [ix-project/ix#9]
`eth_rx_idle_wait` should be driver independent and accessed through an entry of `ix_eth_dev_ops` 
https://github.com/ix-project/ix/blob/master/dp/drivers/ixgbe.c#L379

issue PR: #11

**Comment by aroulin** [comment]
@prekageo: I wonder if you meant we want `eth_rx_idle_wait` to be declared in common as `generic_eth_rx_idle_wait` because it will have to call some driver specific function to check the ready bit like here:
https://github.com/ix-project/ix/blob/master/dp/drivers/ixgbe.c#L399

**Comment by prekageo** [comment]
`eth_rx_idle_wait` is invoked directly by other parts of code. Thus, IX has a direct dependency on this function. This is a mistake. This function should be exported for use through the struct `ix_eth_dev_ops` and should be called indirectly.
